branding:
  name: "EDH Self-Service Center"
  logo_url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Qualcomm-Logo.svg"
  primary_color: "#3253DC"
  secondary_color: "#000000"
  info_color: "#3253DC"
  alert_color: "#D32F2F"
  warning_color: "#FFC107"
  success_color: "#388E3C"

features:
  core: true
  governance: true
  finops: true
  self_service: true
  workflows: true

ui:
  app_switcher: false
  tabs:
    home: true
    my_requests: true
    pending_approvals: true
    training: true
    event_calendar: true
    templates_assets: true
    community_links: true
    admin: true
    reports: true
    training_upload: true
    certification: false
    odps: false
    allowlist: false
    sentinel: false

tools:
  check_allowlist_status: false
  check_github_repo: true
  check_orphaned_assets: true
  does_service_principal_exist: true
  get_workflow_instructions: true
  evaluate_policy: false
  execute_workflow: true
  get_catalog_list: true
  get_cost_summary: true
  get_forecasted_spend: true
  get_resource_efficiency_metrics: false
  get_schema_list: true
  get_table_list: true
  list_github_templates: true
  list_workspaces: true
  search_events: true
  search_requests: true
  search_idp_groups: false
  search_idp_users: false
  check_resource_access: true
  search_approvals: true
  search_user_entitlements: true
  check_tagging_compliance: true
  check_object_permissions: true
  audit_user_access: true
  search_audit_logs: true
  check_overprovisioned_users: true
  check_asset_quality: false
  find_owner: true
  check_training_status: false

workflows:
  RequestType.ALLOWLIST_EXCEPTION: false
  RequestType.ASSET_DEDUPLICATION: false
  RequestType.BATCH_DATA_ACCESS: false
  RequestType.CAMPAIGN: false
  RequestType.CATALOG_SCHEMA_TABLE: true
  RequestType.CATALOG_SCHEMA_TABLE_ACCESS: true
  RequestType.DATA_ACCESS_REQUEST: true
  RequestType.ENFORCEMENT_SENTINEL: false
  RequestType.GITHUB_REPO_CREATION: true
  RequestType.MARKETPLACE_CERTIFICATION: false
  RequestType.PROJECT_ONBOARDING: false
  RequestType.REPORT_EXECUTION: true
  RequestType.REST_API_ACCESS: false
  RequestType.SERVICE_PRINCIPAL: true
  RequestType.SIMPLE_EMAIL: false
  RequestType.WORKSPACE_ACCESS: true
  RequestType.WORKSPACE_PROVISION: true